### ISSUE TITLE
Support for Python 3.8 was dropped, but the badge on the readme still shows Python 3.8

### ISSUE THREAD

**Issue by BioGeek** [hugovk/tinytext#197]
Support for Python 3.8 was [dropped](https://github.com/hugovk/tinytext/commit/e8b021498739831ef2ade70eecb9ab088677ebd8), but the [badge](https://github.com/hugovk/tinytext/blob/be12c8cd4e8a0fa945aa6d8f0e3df552d96f703d/README.md?plain=1#L4C31-L4C112) on the readme still shows Python 3.8:

[![Supported Python versions](https://img.shields.io/pypi/pyversions/tinytext.svg?logo=python&logoColor=FFE873)](https://pypi.org/project/tinytext)

**Comment by hugovk** [comment]
Hello! It's because it's been dropped in the repo, but not yet released to PyPI and the badge reports what is on PyPI.

But I'll do a new release now to update it :)

**Comment by hugovk** [comment]
It now says 3-9-3.13 🚀
