### ISSUE TITLE
Declare support for Python 3.9

### ISSUE THREAD

**Issue by hugovk** [hugovk/tinytext#54]
Python 3.9.0 came out this week.

* https://blog.python.org/2020/10/python-390-is-now-available-and-you-can.html

Let's declare support by adding the 3.9 Trove classifier to `setup.py`.

---

When doing this, if 3.9.0 is available on Travis CI or GitHub Actions (i.e. `3.9`, not `3.9-dev`), also update/add `3.9` to `.travis.yml` or `.github/workflows/test.yml`, 

**Important:** But please test it actually works by enabling the CIs on your fork first. If it does not, only update `setup.py`.

**Comment by ocean** [comment]
Ok, I'm ready to declare ~my love~ support for Python 3.9!
